### ISSUE TITLE
Unable to load script from path!

### ISSUE THREAD

**Issue by mertsahin89** [Tshmofen/verlet-rope-4#4]
Godot 4.2 with gd and mono versions. Throwing an error.

![resim_2024-03-31_204920218](https://github.com/Tshmofen/verlet-rope-4/assets/64549884/2e60bd47-f10c-4ffd-b9ee-8d2b1fa9d09e)

**Comment by Tshmofen** [comment]
Hi! That versions only supports mono, and be sure that you've created a solution with `Project` -> `Tools` -> `C#` -> `Create C# Solution` (If remeber correctly default solution is alredy creating a project with .NET 8, but if there is any errors on build try to change it manually). After you've created it, just try to build the project (it will generate .NET binaries), reload Godot and enable the addon - it should now read the scripts correctly.

I've not included that info in the main repo as those steps affects all the .NET addons and it's expected to be known, but it seems might be useful to include it anyway.

Let me know if those steps are not fixing your issues, hope it helps.

**Comment by zspotter** [comment]
Thank you, worked for me!
